stages:
  - test
  - train

image: python:3.11

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

generate_data:
  stage: test
  script:
    - python src/generate_data.py
    - python src/check_data.py

train_model:
  stage: train
  script:
    - python src/train.py
    - python src/drift_report.py
